spring:
# docker run --name postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres --tmpfs /var/lib/postgresql/data:rw -d postgres
  datasource:
    url: jdbc:postgresql:postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        jdbc:
          lob:
# https://hibernate.atlassian.net/browse/HHH-12368
            non_contextual_creation: true
  flyway:
# FOR DEVELOPMENT, NOT FOR PRODUCTION!
    clean-on-validation-error: true
decorator:
  datasource:
    datasource-proxy:
      logging: slf4j
      query:
        logger-name: com.example.playmock.sql

logging:
  level:
    com.example.playmock.sql: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
